### ISSUE TITLE
Get-DateISO8601

### ISSUE THREAD

**Issue by TechJeeper** [PoshSec/PoshSec#22]
"Get-DateISO8601 : The term 'Get-DateISO8601' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

Where is it getting this cmdlet from?  I see it being called in multiple ps1 files, all of which error out.  (Get-SecSoftwareInstalled.ps1, Get-SecSoftwareIntegrity.ps1, ect)

Thanks!
Cody

**Comment by jwgoerlich** [comment]
The Get-DateISO8601 cmdlet is in the PoshSec.PowerShell.Commands.dll file.

**Comment by TechJeeper** [comment]
Hmmm - thanks, I will try to figure out why the .dll isn't loading properly.
