### ISSUE TITLE
Get-SystemUpTime missing Error Handling

### ISSUE THREAD

**Issue by ghost** [PoshSec/PoshSec#39]
When the Get-SystemUpTime script https://github.com/Jrotenberger/PoshSec/blob/development/Forensics/Get-SystemUptime.ps1 submitted by https://github.com/Jrotenberger/ is missing -ErrorVariable variable -ErrorAction SilentlyContinue or similar.

When an invalid system name is submitted to computer or computerlist, it will fail with an RPC error. Those errors should be captured in an -ErrorVariable and checked before the object is processed.

For example:

```
wmi = Get-WmiObject -ComputerName $computer -Query "SELECT LastBootUpTime FROM Win32_OperatingSystem" -ErrorVariable myerror -ErrorAction SilentlyContinue
    if($myerror.count -eq 0)
    {
      $now = Get-Date
      $boottime = $wmi.ConvertToDateTime($wmi.LastBootUpTime)
      $uptime = $now - $boottime
      $d =$uptime.days
      $h =$uptime.hours
      $m =$uptime.Minutes
      $s = $uptime.Seconds
      $Computerobj.ComputerName = $computer
      $Computerobj.Uptime = "$d Days $h Hours $m Min $s Sec"
      $Computerobj.LastReboot = $boottime
      $Computerobj   
    } 
```

**Comment by Jrotenberger** [comment]
Fixed it today - 3/20/2014
