### ISSUE TITLE
Start-SecBaseline typo

### ISSUE THREAD

**Issue by jvucic** [PoshSec/PoshSec#66]
Calls "Get-SecFiles", but is most likely ref'ing "Get-SecFile"

**Comment by jvucic** [comment]
Calls "Get-SecDeviceList", but is most likely ref'ing "Get-SecDeviceInventory"

**Comment by mwjcomputing** [comment]
I will work a fix and push it soon.

**Comment by mwjcomputing** [comment]
Fixed with recent push.
